chore (file_response): implement macro for crystal version check
luckyframework/lucky pull request #1918
Opened 2024-10-11 20:55 UTC by aarcex3

## Purpose
Fixes #1899

## Description

Implemented a macro to check the crystal version. This is to handle the deprecation of `File.readable?` since version 1.13 in favour of `File::Info.readable?`

## Checklist
* [x] - An issue already exists detailing the issue/or feature request that this PR fixes
* [x] - All specs are formatted with `crystal tool format spec src`
* [ ] - Inline documentation has been added and/or updated
* [x] - Lucky builds on docker with `./script/setup`
* [x] - All builds and specs pass on docker with `./script/test`

2024-10-11 20:56 UTC, aarcex3 commented
I'm not very familiar with crystal in general.
I tried to refactor the logic and put it into `src/run_macros/` but no luck.
Any tips on how to improve it?
Thanks

2024-10-11 21:05 UTC, jwoertink requested changes
This is great! Thanks for taking this on. Just a small change to user Crystal's built-in version comparison https://crystal-lang.org/api/1.14.0/Crystal/Macros.html#compare_versions(v1:StringLiteral,v2:StringLiteral):NumberLiteral-instance-method then I think we should be good.

2024-10-11 21:05 UTC, jwoertink commented on src/lucky/file_response.cr
> +  {% if Crystal::VERSION.split(".")[0].to_i > 1 || (Crystal::VERSION.split(".")[0].to_i == 1 && Crystal::VERSION.split(".")[1].to_i > 12) || (Crystal::VERSION.split(".")[0].to_i == 1 && Crystal::VERS
```suggestion
  {% if compare_versions(Crystal::VERSION, "1.13.0") >= 0 %}
```

2024-10-13 16:17 UTC, jwoertink approved these changes
Thanks so much for doing this. Those CI failures are unrelated and I'll fix those later. This looks good! :+1:

2024-10-13 16:17 UTC, merged